const char *readme_text =
"   64kformat by koutsie   \n"
"   Version " __DATE__ "   \n"
"   https://the-sauna.icu/64kformat/   \n"
"\n"
"This tool has just formatted your memory card to FAT32 with a 64 KB cluster size "
"and a properly sized IPL sector so DC_ARK works correctly.\n"
"The PSP's built-in formatter only creates FAT32 with 32 KB clusters.\n"
"\n"
"Using 64 KB clusters significantly improves SD card read performance, "
"resulting in faster load times across the system.\n"
"\n"
"Big shoutouts to Turan, shinz and TotalKommando for testing, to the PSP Homebrew Community "
"for their support, and to you for using 64kformat!\n"
"\n"
"For more information and test results:\n"
"https://docs.google.com/spreadsheets/d/1PJH87w-2Rn7Xk15KIuWYOKhmGYnk6tHr5BX3VOFBjWQ/edit\n"
"\n"
"For the AIO Drop-In SD Starter Package:\n"
"https://www.komstation.com/resource/kommandos-psp-drop-in-package/\n";
